[package]
name = "gauc"
version = "0.8.1"
authors = []

[lib]
name = "gauc"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
byteorder = "1.1"
gauc = "0.8"
lazy_static = "0.2"
rustler = "0.16"
rustler_codegen = "0.16"
uuid = { version = "0.5", features = ["v4"] }
